#!python3
import tkinter as tk
Window=tk.Tk()
Window.title=("tkk")
Window.geometry=("2000x2000")
buttin1=tk.Entry(Window,width=20)
buttin2=tk.Entry(Window,width=15)
buttin3=tk.Entry(Window,width=15)
buttin4=tk.Entry(Window,width=15)
buttin5=tk.Entry(Window,width=15)
buttin6=tk.Entry(Window,width=15)
click1=tk.Button(Window,text="< Previous")
click2=tk.Button(Window,text="Save Entry")
click3=tk.Button(Window,text="Next>")
lable1=tk.Button(Window,text="Search By Name")
lable2=tk.Label(Window,text="Client Database")
lable3=tk.Label(Window,text="Name")
lable4=tk.Label(Window,text="Type")
lable5=tk.Label(Window,text="Breed")
lable6=tk.Label(Window,text="Owner")
lable7=tk.Label(Window,text="Birthdate")
dogphotot= tk.PhotoImage(file="dog.png")
label9 = tk.Label(Window, image=dogphotot)


lable1.grid(row=0,column=4)
buttin1.grid(row=0,column=5)
lable2.grid(row=1,column=3)
lable3.grid(row=3,column=1)
lable4.grid(row=3,column=2)
lable5.grid(row=3,column=3)
lable6.grid(row=3,column=4)
lable7.grid(row=3,column=5)
buttin2.grid(row=4,column=5)
buttin3.grid(row=4,column=4)
buttin4.grid(row=4,column=3)
buttin5.grid(row=4,column=2)
buttin6.grid(row=4,column=1)
click1.grid(row=5,column=1)
click2.grid(row=5,column=3)
click3.grid(row=5,column=5)
label9.grid(row=1,column=1,columnspan=1)
Window.mainloop()